### ISSUE TITLE
AI-初识AI部分 图片挂科学上网强制刷新后才会加载出来

### ISSUE THREAD

**Issue by W1ndys** [ProbiusOfficial/Hello-CTF#116]
传送门：https://hello-ctf.com/HC_AI/What_is_AI/#tensorflow

一开始以为是代码写错了，看了下源码没问题，以为是我网络问题

实测发现开科学上网后强制刷新才会加载出来图片，看了下其他图片都放在 assets 了，没有这个问题

是否考虑一下把图片下载之后放到 Github 里（

![image](https://github.com/ProbiusOfficial/Hello-CTF/assets/109416673/cfda1fb6-2eca-499d-8332-05a03d5402d9)

**Comment by n-WN** [comment]
commit 63dfdae,  fixed it
