### ISSUE TITLE
日间模式链接显示问题

### ISSUE THREAD

**Issue by L4ntern0** [ProbiusOfficial/Hello-CTF#129]
![image](https://github.com/user-attachments/assets/26b55c4f-cdef-434a-b869-59e06a46e45b)
![image](https://github.com/user-attachments/assets/32fec6bf-f675-4f03-b113-8b3a5b3d879e)

在日间模式下，链接🔗全是白的

**Comment by shenghuo2** [comment]
虽然我能复现这个bug，但是不是很稳定，请问师傅的浏览器和设备是？

**Comment by L4ntern0** [comment]
Chrome: Version 131.0.6778.86 (Official Build) (arm64)
MacBook Pro

**Comment by shenghuo2** [comment]
果然，我也是mac
貌似是
```
.md-typeset a {
    color: var(--md-typeset-a-color);
    word-break:break-word
}
```
中`--md-typeset-a-color`的颜色计算错误的情况下触发的
貌似是mkdocs-material的问题 @ProbiusOfficial

**Comment by L4ntern0** [comment]
> 已经在commit [4ae2278](https://github.com/ProbiusOfficial/Hello-CTF/commit/4ae22785154ee2c66041858ae5a195183c5155a8)中尝试进行了修复。辛苦再次访问并测试一下，看看问题是否已经解决。

已解决
