### ISSUE TITLE
Reverse版块图片加载不出来，可能是图片路径“/”打成了“\”导致的？

### ISSUE THREAD

**Issue by Pisces032** [ProbiusOfficial/Hello-CTF#78]
`![p1-1](.\Images\p1-1.png)`
mkdocs本地测试的时候`\` `/`都能识别，但是上传到GithubPages似乎只能识别`/`。
之前正常的版块也都是用的`/`。

**Comment by Randark-JMT** [comment]
具体的相关细节可以参考这篇 stackoverflow 的回答

[So what IS the right direction of the path's slash (/ or \) under Windows? - stackoverflow](https://stackoverflow.com/questions/1589930/so-what-is-the-right-direction-of-the-paths-slash-or-under-windows)

为了最大的兼容性，请使用相对路径和左斜杠 / 进行编写
