### ISSUE TITLE
逆向教程中似乎有typo

### ISSUE THREAD

**Issue by AegeanYan** [ProbiusOfficial/Hello-CTF#86]
https://github.com/ProbiusOfficial/Hello-CTF/blob/5d9c865a2ebbf9a605ec69fa1c66d4181b5bcc61/docs/HC_Reverse/Quick%20Start%EF%BC%9AASM%E6%B1%87%E7%BC%96.md?plain=1#L64

此处没有看到减一操作

**Comment by FrexCheat** [comment]
`loop` 命令每执行一次，储存计次的 `cx` 寄存器会自行递减1，这个操作是默认的。
